[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "opened-gate"
version = "0.0.5"

dependencies = [ # main dependencies (for pip)
    "importlib-metadata",
    "numpy",
    "torch",
    "torchvision",
    "omegaconf",
    "lightning",
    "boto3",
    "s3fs",
    "dvc",
    "dvc-s3",
    "icecream",
]

[project.optional-dependencies] # optional dependency groups (for pip)
dev = ["black", "flake8", "isort", "pre-commit", "pytest", "pytest-cov"]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["src/tests"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/yolonas -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
