name: build package
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Show version
        run: |
          python -c "import opened_gate; print(opened_gate.__version__)"
